/*
 * Copyright 2017-present, Yudong (Dom) Wang
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var APIDATA = {
  "api_description" : {
    "title" : "问诊平台 RESTful API",
    "summary" : "This RESTful API document is generated by <a class=\"wistool\" href=\"https://github.com/Wisdom-Projects/rest-client\">Wisdom RESTClient."
  },
  "api_list" : [ {
    "api_summary" : {
      "title" : "Create chunyu_question_close",
      "method" : "POST",
      "path" : "/v1/chunyu_question_close"
    },
    "api_request" : {
      "header" : "Accept : application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain\r\nContent-Type : application/json; charset=UTF-8\r\n",
      "model" : "   problem_id [number]\r\n   user_id [string]\r\n   sign [string]\r\n   atime [number]\r\n   status [string]\r\n   msg [string]\r\n   price [number]\r\n",
      "example" : "{\n  &quot;problem_id&quot;: 1,\n  &quot;user_id&quot;: &quot;123456&quot;,\n  &quot;sign&quot;: &quot;12345abcde&quot;,\n  &quot;atime&quot;: 137322417,\n  &quot;status&quot;: &quot;close&quot;,\n  &quot;msg&quot;: &quot;close&quot;,\n  &quot;price&quot;: 10000\n}"
    },
    "api_response" : [ {
      "status" : "HTTP/1.1 200 ",
      "code" : 200,
      "message" : "OK",
      "model" : "   error [number]\r\n   error_msg [string]\r\n",
      "example" : "{\n  &quot;error&quot;: 0,\n  &quot;error_msg&quot;: &quot;&quot;\n}"
    } ]
  }, {
    "api_summary" : {
      "title" : "Create get_clinic_doctors",
      "method" : "POST",
      "path" : "/v1/get_clinic_doctors"
    },
    "api_request" : {
      "header" : "Accept : application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain\r\nContent-Type : application/json; charset=UTF-8\r\n",
      "model" : "   user_id [string]\r\n   clinic_no [string]\r\n   province [string]\r\n   city [string]\r\n   per_page [number]\r\n   page [number]\r\n",
      "example" : "{\n  &quot;user_id&quot;: &quot;123456&quot;,\n  &quot;clinic_no&quot;: &quot;11&quot;,\n  &quot;province&quot;: &quot;&#27993;&#27743;&quot;,\n  &quot;city&quot;: &quot;&#26477;&#24030;&quot;,\n  &quot;per_page&quot;: 10,\n  &quot;page&quot;: 0\n}"
    },
    "api_response" : [ {
      "status" : "HTTP/1.1 200 ",
      "code" : 200,
      "message" : "OK",
      "model" : "   errcode [string]\r\n   msg [string]\r\n   data [object]\r\n    &#9500;&#9472;&#9472;doctors [array]\r\n    &#9474;   &#9500;&#9472;&#9472;clinic_name [string]\r\n    &#9474;   &#9500;&#9472;&#9472;good_at [string]\r\n    &#9474;   &#9500;&#9472;&#9472;hospital_name [string]\r\n    &#9474;   &#9500;&#9472;&#9472;image [string]\r\n    &#9474;   &#9500;&#9472;&#9472;id [string]\r\n    &#9474;   &#9500;&#9472;&#9472;name [string]\r\n    &#9474;   &#9500;&#9472;&#9472;price [number]\r\n    &#9474;   &#9500;&#9472;&#9472;purchase_num [number]\r\n    &#9474;   &#9500;&#9472;&#9472;title [string]\r\n    &#9474;   &#9500;&#9472;&#9472;is_famous_doctor [boolean]\r\n    &#9500;&#9472;&#9472;error [number]\r\n    &#9500;&#9472;&#9472;error_msg [string]\r\n   page [object]\r\n    &#9500;&#9472;&#9472;current [number]\r\n",
      "example" : "{\n  &quot;errcode&quot;: &quot;0&quot;,\n  &quot;msg&quot;: &quot;&quot;,\n  &quot;data&quot;: {\n    &quot;doctors&quot;: [\n      {\n        &quot;clinic_name&quot;: &quot;&#22919;&#31185;&quot;,\n        &quot;good_at&quot;: &quot;&#25797;&#38271;&#35813;&#25797;&#38271;&#30340;&#65292;&#19981;&#22815;&#22235;&#21313;&#20010;&#23383;&#23558;&#20852;&#24314;&#22320;&#19979;&#26469;&#23601;&#22823;&#23478;&#37117;&#24456;&#22810;&#24456;&#22810;&#24456;&#20320;&#25165;&#21507;&#30340;&#26469;&#21679;&#33707;&#36807;&#20110;&#32463;&#27982;&#23398;&#65292;&#22909;&#20687;&#21507;&#20102;&#38754;&#26465; \\r\\n\\r\\n&quot;,\n        &quot;hospital_name&quot;: &quot;&#21271;&#20140;&#21327;&#21644;&#21307;&#38498;&quot;,\n        &quot;image&quot;: &quot;https://media2.chunyuyisheng.com/@/media/images/2016/03/29/61ad355d8b47_w180_h180_.jpg?imageMogr2/thumbnail/150x&quot;,\n        &quot;id&quot;: &quot;clinic_chanke_zhangrongya&quot;,\n        &quot;name&quot;: &quot;&#31456;&#33993;&#23045;2&quot;,\n        &quot;price&quot;: 100,\n        &quot;purchase_num&quot;: 2395,\n        &quot;title&quot;: &quot;&#21103;&#20027;&#20219;&#21307;&#24072;&quot;,\n        &quot;is_famous_doctor&quot;: false\n      },\n      {\n        &quot;clinic_name&quot;: &quot;&#22919;&#31185;&quot;,\n        &quot;good_at&quot;: &quot;&#30333;&#20113;&#20598;&#23572;&#20250;&#36974;&#20303;&#34013;&#22825;&#65292;&#20294;&#34013;&#22825;&#27704;&#36828;&#22312;&#30333;&#20113;&#20043;&#19978;&#65281;djdidkdkdoskdjdkxnkd\\r\\n&#36151;&#27454;&#26041;&#35299;&#25918;&#23425;&#22799;&#20030;&#34892;&#21335;&#38750;&#20030;&#34892;&#24180;&#24230;&#20915;&#23450;&#20026;&#20154;&#29238;&#27597;&quot;,\n        &quot;hospital_name&quot;: &quot;&#37073;&#24030;&#22823;&#23398;&#31532;&#19968;&#38468;&#23646;&#21307;&#38498;&quot;,\n        &quot;image&quot;: &quot;https://media3.chunyuyisheng.com/hzsAAKj0y1RiKmwU-181f684d-904c-4e36-bd3e-2eb0098a3074_w576_h576.png?imageMogr2/thumbnail/150x&quot;,\n        &quot;id&quot;: &quot;b092c63582871cc0&quot;,\n        &quot;name&quot;: &quot;&#21608;&#29618;&quot;,\n        &quot;price&quot;: 100,\n        &quot;purchase_num&quot;: 1784,\n        &quot;title&quot;: &quot;&#20027;&#20219;&#21307;&#24072;&quot;,\n        &quot;is_famous_doctor&quot;: false\n      }\n    ],\n    &quot;error&quot;: 0,\n    &quot;error_msg&quot;: &quot;&quot;\n  },\n  &quot;page&quot;: {\n    &quot;current&quot;: 0\n  }\n}"
    } ]
  }, {
    "api_summary" : {
      "title" : "Create create_paid_problem",
      "method" : "POST",
      "path" : "/v1/create_paid_problem"
    },
    "api_request" : {
      "header" : "Accept : application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain\r\nContent-Type : application/json; charset=UTF-8\r\n",
      "model" : "   user_id [string]\r\n   clinic_no [string]\r\n   content [string]\r\n   partner_order_id [string]\r\n   pay_type [string]\r\n   Platform [string]\r\n",
      "example" : "{\n  &quot;user_id&quot;: &quot;123456&quot;,\n  &quot;clinic_no&quot;: &quot;1&quot;,\n  &quot;content&quot;: &quot;&#24863;&#20882;&#20102;&quot;,\n  &quot;partner_order_id&quot;: &quot;123abc&quot;,\n  &quot;pay_type&quot;: &quot;qc_hospital_common&quot;,\n  &quot;Platform&quot;: &quot;chunyu&quot;\n}"
    },
    "api_response" : [ {
      "status" : "HTTP/1.1 200 ",
      "code" : 200,
      "message" : "OK",
      "model" : "   errcode [string]\r\n   msg [string]\r\n   data [object]\r\n    &#9500;&#9472;&#9472;problem_id [number]\r\n    &#9500;&#9472;&#9472;error [number]\r\n    &#9500;&#9472;&#9472;error_msg [string]\r\n   page [object]\r\n    &#9500;&#9472;&#9472;current [number]\r\n",
      "example" : "{\n  &quot;errcode&quot;: &quot;0&quot;,\n  &quot;msg&quot;: &quot;&quot;,\n  &quot;data&quot;: {\n    &quot;problem_id&quot;: 0,\n    &quot;error&quot;: 1,\n    &quot;error_msg&quot;: &quot;&#35299;&#26512;&#22833;&#36133;&quot;\n  },\n  &quot;page&quot;: {\n    &quot;current&quot;: 0\n  }\n}"
    } ]
  }, {
    "api_summary" : {
      "title" : "Create get_recommended_doctors",
      "method" : "POST",
      "path" : "/v1/get_recommended_doctors"
    },
    "api_request" : {
      "header" : "Accept : application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain\r\nContent-Type : application/json; charset=UTF-8\r\n",
      "model" : "   user_id [string]\r\n   ask [string]\r\n",
      "example" : "{\n  &quot;user_id&quot;: &quot;123456&quot;,\n  &quot;ask&quot;: &quot;&#24863;&#20882;&#20102;&quot;\n}"
    },
    "api_response" : [ {
      "status" : "HTTP/1.1 200 ",
      "code" : 200,
      "message" : "OK",
      "model" : "   errcode [string]\r\n   msg [string]\r\n   data [object]\r\n    &#9500;&#9472;&#9472;doctors [array]\r\n    &#9474;   &#9500;&#9472;&#9472;clinic_name [string]\r\n    &#9474;   &#9500;&#9472;&#9472;good_at [string]\r\n    &#9474;   &#9500;&#9472;&#9472;hospital_name [string]\r\n    &#9474;   &#9500;&#9472;&#9472;image [string]\r\n    &#9474;   &#9500;&#9472;&#9472;id [string]\r\n    &#9474;   &#9500;&#9472;&#9472;name [string]\r\n    &#9474;   &#9500;&#9472;&#9472;price [number]\r\n    &#9474;   &#9500;&#9472;&#9472;purchase_num [number]\r\n    &#9474;   &#9500;&#9472;&#9472;title [string]\r\n    &#9474;   &#9500;&#9472;&#9472;is_famous_doctor [boolean]\r\n    &#9500;&#9472;&#9472;error [number]\r\n    &#9500;&#9472;&#9472;error_msg [string]\r\n   page [object]\r\n    &#9500;&#9472;&#9472;current [number]\r\n",
      "example" : "{\n  &quot;errcode&quot;: &quot;0&quot;,\n  &quot;msg&quot;: &quot;&quot;,\n  &quot;data&quot;: {\n    &quot;doctors&quot;: [\n      {\n        &quot;clinic_name&quot;: &quot;&#22919;&#31185;&quot;,\n        &quot;good_at&quot;: &quot;&#25797;&#38271;&#35813;&#25797;&#38271;&#30340;&#65292;&#19981;&#22815;&#22235;&#21313;&#20010;&#23383;&#23558;&#20852;&#24314;&#22320;&#19979;&#26469;&#23601;&#22823;&#23478;&#37117;&#24456;&#22810;&#24456;&#22810;&#24456;&#20320;&#25165;&#21507;&#30340;&#26469;&#21679;&#33707;&#36807;&#20110;&#32463;&#27982;&#23398;&#65292;&#22909;&#20687;&#21507;&#20102;&#38754;&#26465; \\r\\n\\r\\n&quot;,\n        &quot;hospital_name&quot;: &quot;&#21271;&#20140;&#21327;&#21644;&#21307;&#38498;&quot;,\n        &quot;image&quot;: &quot;https://media2.chunyuyisheng.com/@/media/images/2016/03/29/61ad355d8b47_w180_h180_.jpg?imageMogr2/thumbnail/150x&quot;,\n        &quot;id&quot;: &quot;clinic_chanke_zhangrongya&quot;,\n        &quot;name&quot;: &quot;&#31456;&#33993;&#23045;2&quot;,\n        &quot;price&quot;: 100,\n        &quot;purchase_num&quot;: 2394,\n        &quot;title&quot;: &quot;&#21103;&#20027;&#20219;&#21307;&#24072;&quot;,\n        &quot;is_famous_doctor&quot;: false\n      },\n      {\n        &quot;clinic_name&quot;: &quot;&#22919;&#31185;&quot;,\n        &quot;good_at&quot;: &quot;&#30333;&#20113;&#20598;&#23572;&#20250;&#36974;&#20303;&#34013;&#22825;&#65292;&#20294;&#34013;&#22825;&#27704;&#36828;&#22312;&#30333;&#20113;&#20043;&#19978;&#65281;djdidkdkdoskdjdkxnkd\\r\\n&#36151;&#27454;&#26041;&#35299;&#25918;&#23425;&#22799;&#20030;&#34892;&#21335;&#38750;&#20030;&#34892;&#24180;&#24230;&#20915;&#23450;&#20026;&#20154;&#29238;&#27597;&quot;,\n        &quot;hospital_name&quot;: &quot;&#37073;&#24030;&#22823;&#23398;&#31532;&#19968;&#38468;&#23646;&#21307;&#38498;&quot;,\n        &quot;image&quot;: &quot;https://media3.chunyuyisheng.com/hzsAAKj0y1RiKmwU-181f684d-904c-4e36-bd3e-2eb0098a3074_w576_h576.png?imageMogr2/thumbnail/150x&quot;,\n        &quot;id&quot;: &quot;b092c63582871cc0&quot;,\n        &quot;name&quot;: &quot;&#21608;&#29618;&quot;,\n        &quot;price&quot;: 100,\n        &quot;purchase_num&quot;: 1784,\n        &quot;title&quot;: &quot;&#20027;&#20219;&#21307;&#24072;&quot;,\n        &quot;is_famous_doctor&quot;: false\n      }\n    ],\n    &quot;error&quot;: 0,\n    &quot;error_msg&quot;: &quot;&quot;\n  },\n  &quot;page&quot;: {\n    &quot;current&quot;: 0\n  }\n}"
    } ]
  }, {
    "api_summary" : {
      "title" : "Create create_free_problem",
      "method" : "POST",
      "path" : "/v1/create_free_problem"
    },
    "api_request" : {
      "header" : "Accept : application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain\r\nContent-Type : application/json; charset=UTF-8\r\n",
      "model" : "   user_id [string]\r\n   content [string]\r\n   Platform [string]\r\n   clinic_no [string]\r\n",
      "example" : "{\n  &quot;user_id&quot;: &quot;1234567&quot;,\n  &quot;content&quot;: &quot;[ {\\u0027type\\u0027: \\u0027patient_meta\\u0027, \\u0027age\\u0027: \\u002715 \\u0027, \\u0027sex\\u0027: \\u0027o\\u0027}, {\\u0027type\\u0027: \\u0027text\\u0027, \\u0027text\\u0027: \\u0027helo\\u0027}]&quot;,\n  &quot;Platform&quot;: &quot;chunyu&quot;,\n  &quot;clinic_no&quot;: &quot;1&quot;\n}"
    },
    "api_response" : [ {
      "status" : "HTTP/1.1 200 ",
      "code" : 200,
      "message" : "OK",
      "model" : "   errcode [string]\r\n   msg [string]\r\n   data [object]\r\n    &#9500;&#9472;&#9472;problem_id [number]\r\n    &#9500;&#9472;&#9472;error [number]\r\n    &#9500;&#9472;&#9472;error_msg [string]\r\n   page [object]\r\n    &#9500;&#9472;&#9472;current [number]\r\n",
      "example" : "{\n  &quot;errcode&quot;: &quot;0&quot;,\n  &quot;msg&quot;: &quot;&quot;,\n  &quot;data&quot;: {\n    &quot;problem_id&quot;: 0,\n    &quot;error&quot;: 1,\n    &quot;error_msg&quot;: &quot;&#35299;&#26512;&#22833;&#36133;&quot;\n  },\n  &quot;page&quot;: {\n    &quot;current&quot;: 0\n  }\n}"
    } ]
  }, {
    "api_summary" : {
      "title" : "Create create_oriented_problem",
      "method" : "POST",
      "path" : "/v1/create_oriented_problem"
    },
    "api_request" : {
      "header" : "Accept : application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain\r\nContent-Type : application/json; charset=UTF-8\r\n",
      "model" : "   user_id [string]\r\n   doctor_ids [string]\r\n   content [string]\r\n   partner_order_id [string]\r\n   price [number]\r\n   platform [string]\r\n",
      "example" : "{\n  &quot;user_id&quot;: &quot;123456&quot;,\n  &quot;doctor_ids&quot;: &quot;b092c63582871cc0&quot;,\n  &quot;content&quot;: &quot;[{\\u0027type\\u0027: \\u0027text\\u0027,\\u0027text\\u0027:\\u0027&#36825;&#26159;&#19968;&#27573;&#25991;&#26412;&#24418;&#24335;&#30340;&#20869;&#23481;\\u0027}, {\\u0027type\\u0027: \\u0027patient_meta\\u0027,\\u0027age\\u0027: \\u002715&#23681;\\u0027,\\u0027sex\\u0027: \\u0027&#30007;\\u0027}]&quot;,\n  &quot;partner_order_id&quot;: &quot;0111222333abs&quot;,\n  &quot;price&quot;: 10000,\n  &quot;platform&quot;: &quot;chunyu&quot;\n}"
    },
    "api_response" : [ {
      "status" : "HTTP/1.1 200 ",
      "code" : 200,
      "message" : "OK",
      "model" : "   errcode [string]\r\n   msg [string]\r\n   data [object]\r\n    &#9500;&#9472;&#9472;problems [null]\r\n    &#9500;&#9472;&#9472;error [number]\r\n    &#9500;&#9472;&#9472;error_msg [string]\r\n   page [object]\r\n    &#9500;&#9472;&#9472;current [number]\r\n",
      "example" : "{\n  &quot;errcode&quot;: &quot;0&quot;,\n  &quot;msg&quot;: &quot;&quot;,\n  &quot;data&quot;: {\n    &quot;problems&quot;: null,\n    &quot;error&quot;: 1,\n    &quot;error_msg&quot;: &quot;&#35299;&#26512;&#22833;&#36133;&quot;\n  },\n  &quot;page&quot;: {\n    &quot;current&quot;: 0\n  }\n}"
    } ]
  }, {
    "api_summary" : {
      "title" : "Create patient_login",
      "method" : "POST",
      "path" : "/v1/patient_login"
    },
    "api_request" : {
      "header" : "Accept : application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain\r\nContent-Type : application/json; charset=UTF-8\r\n",
      "model" : "   user_id [string]\r\n   password [string]\r\n   platform [string]\r\n",
      "example" : "{\n  &quot;user_id&quot;: &quot;123456&quot;,\n  &quot;password&quot;: &quot;654321&quot;,\n  &quot;platform&quot;: &quot;chunyu&quot;\n}"
    },
    "api_response" : [ {
      "status" : "HTTP/1.1 200 ",
      "code" : 200,
      "message" : "OK",
      "model" : "   errcode [string]\r\n   msg [string]\r\n   data [object]\r\n    &#9500;&#9472;&#9472;error [number]\r\n    &#9500;&#9472;&#9472;error_msg [string]\r\n   page [object]\r\n    &#9500;&#9472;&#9472;current [number]\r\n",
      "example" : "{\n  &quot;errcode&quot;: &quot;0&quot;,\n  &quot;msg&quot;: &quot;&quot;,\n  &quot;data&quot;: {\n    &quot;error&quot;: 0,\n    &quot;error_msg&quot;: &quot;user logged in ok&quot;\n  },\n  &quot;page&quot;: {\n    &quot;current&quot;: 0\n  }\n}"
    } ]
  }, {
    "api_summary" : {
      "title" : "Create chunyu_doctor_response",
      "method" : "POST",
      "path" : "/v1/chunyu_doctor_response"
    },
    "api_request" : {
      "header" : "Accept : application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain\r\nContent-Type : application/json; charset=UTF-8\r\n",
      "model" : "   problem_id [number]\r\n   user_id [string]\r\n   sign [string]\r\n   atime [number]\r\n   content [string]\r\n   is_summary [boolean]\r\n   doctor [object]\r\n    &#9500;&#9472;&#9472;id [string]\r\n    &#9500;&#9472;&#9472;name [string]\r\n    &#9500;&#9472;&#9472;image [string]\r\n    &#9500;&#9472;&#9472;title [string]\r\n    &#9500;&#9472;&#9472;level_title [string]\r\n    &#9500;&#9472;&#9472;clinic [string]\r\n    &#9500;&#9472;&#9472;clinic_no [string]\r\n    &#9500;&#9472;&#9472;hospital [string]\r\n    &#9500;&#9472;&#9472;hospital_grade [string]\r\n    &#9500;&#9472;&#9472;good_at [string]\r\n",
      "example" : "{\n  &quot;problem_id&quot;: 1,\n  &quot;user_id&quot;: &quot;123456&quot;,\n  &quot;sign&quot;: &quot;12345abcde&quot;,\n  &quot;atime&quot;: 137322417,\n  &quot;content&quot;: &quot;[ {\\u0027type\\u0027: \\u0027text\\u0027,\\u0027text\\u0027: \\u0027&#36825;&#26159;&#19968;&#27573;&#25991;&#26412;&#24418;&#24335;&#30340;&#20869;&#23481;\\u0027},{\\u0027type\\u0027: \\u0027image\\u0027,\\u0027file\\u0027: \\u0027&#36825;&#26159;&#22270;&#29255;&#24418;&#24335;&#30340;&#20869;&#23481;,&#36825;&#37324;&#26159;&#22270;&#29255;&#30340; url\\u0027},{\\u0027type\\u0027: \\u0027audio\\u0027,\\u0027file\\u0027: \\u0027&#36825;&#26159;&#35821;&#38899;&#24418;&#24335;&#30340;&#20869;&#23481;,&#36825;&#37324;&#26159;&#38899;&#39057;&#25991;&#20214;&#30340; url\\u0027}]&quot;,\n  &quot;is_summary&quot;: true,\n  &quot;doctor&quot;: {\n    &quot;id&quot;: &quot;&#21307;&#29983; ID&quot;,\n    &quot;name&quot;: &quot;&#29579;&#38050;&#34507;&quot;,\n    &quot;image&quot;: &quot;&#21307;&#29983;&#29031;&#29255;&#30340; url&quot;,\n    &quot;title&quot;: &quot;&#21307;&#29983;&#32844;&#31216;&quot;,\n    &quot;level_title&quot;: &quot;&#24102;&#21307;&#38498;&#32423;&#21035;&#30340;&#21307;&#29983;&#32844;&#31216;&quot;,\n    &quot;clinic&quot;: &quot;&#31185;&#23460;&quot;,\n    &quot;clinic_no&quot;: &quot;&#31185;&#23460;&#21495;&quot;,\n    &quot;hospital&quot;: &quot;&#21327;&#21644;&#21307;&#38498;&quot;,\n    &quot;hospital_grade&quot;: &quot;&#19977;&#32423;&#30002;&#31561;&quot;,\n    &quot;good_at&quot;: &quot;&#20869;&#31185;, &#22806;&#31185;&quot;\n  }\n}"
    },
    "api_response" : [ {
      "status" : "HTTP/1.1 200 ",
      "code" : 200,
      "message" : "OK",
      "model" : "   error [number]\r\n   error_msg [string]\r\n",
      "example" : "{\n  &quot;error&quot;: 0,\n  &quot;error_msg&quot;: &quot;&quot;\n}"
    } ]
  } ]
};
