/*
 * Copyright 2017-present, Yudong (Dom) Wang
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var APIDATA = {
  "api_description" : {
    "title" : "RESTful API",
    "summary" : "This RESTful API document is generated by <a class=\"wistool\" href=\"https://github.com/Wisdom-Projects/rest-client\">Wisdom RESTClient."
  },
  "api_list" : [ {
    "api_summary" : {
      "title" : "Create patient_login",
      "method" : "POST",
      "path" : "/v1/patient_login"
    },
    "api_request" : {
      "header" : "Content-Type : application/json; charset=UTF-8\r\nAccept : application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain\r\n",
      "model" : "   user_id [string]\r\n   password [string]\r\n   platform [string]\r\n",
      "example" : "{\n  &quot;user_id&quot;: &quot;123456&quot;,\n  &quot;password&quot;: &quot;654321&quot;,\n  &quot;platform&quot;: &quot;chunyu&quot;\n}"
    },
    "api_response" : [ {
      "status" : "HTTP/1.1 200 ",
      "code" : 200,
      "message" : "OK",
      "model" : "   errcode [string]\r\n   msg [string]\r\n   data [object]\r\n    &#9500;&#9472;&#9472;error [number]\r\n    &#9500;&#9472;&#9472;error_msg [string]\r\n   page [object]\r\n    &#9500;&#9472;&#9472;current [number]\r\n",
      "example" : "{\n  &quot;errcode&quot;: &quot;0&quot;,\n  &quot;msg&quot;: &quot;&quot;,\n  &quot;data&quot;: {\n    &quot;error&quot;: 0,\n    &quot;error_msg&quot;: &quot;user logged in ok&quot;\n  },\n  &quot;page&quot;: {\n    &quot;current&quot;: 0\n  }\n}"
    } ]
  } ]
};
